### ISSUE TITLE
Decode gives me skewed image

### ISSUE THREAD

**Issue by TeofilisMartisius** [vzhn/ffmpeg-java-samples#1]
Hi,

This example was one of the first first things that came up on google search for MKV h.264 Java decoding and it was giving me some problems, hence I thought I'll contact you.

I was testing it on 64 bit Linux with org.bytedeco:ffmpeg:4.4-1.5.6 and same version of ffmpeg-platform dependency.

It was giving me skewed images. I found that fixing following solved the problem:

https://github.com/vzhn/ffmpeg-java-samples/blob/1c16166068dc1bb4b6e49bd9c2b51176733387ea/src/main/java/DemuxAndDecodeH264.java#L139

Should be AV_PIX_FMT_BGR24 as that's the format that's being used for Java BufferedImage on line 151.

Also, https://github.com/vzhn/ffmpeg-java-samples/blob/1c16166068dc1bb4b6e49bd9c2b51176733387ea/src/main/java/DemuxAndDecodeH264.java#L147 should be 24 bits, as we're using 3 byte pixels.

Changing these two parameters fixed the problem for me. It might solve it for others as well, so I'd consider fixing this upstream.

Sincerely,
Teofilis Martisius

**Comment by vzhn** [comment]
Hi! Thank you for contribution.

`24` is byte alignment. I have changed it to 1, so this should work now. Please check, and if it OK, close the ticket.
